version: '3'
services:
  react-app:
    build: ./client
    image: okdev713/kid-react-app
    container_name: kid-react-app
    command: serve -s build
    environment: 
      NODE_ENV: production
    ports: 
      - 5000:5000
  nodejs:
    build: ./server
    image: okdev713/kid-express-app
    container_name: kid-express-app
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    command: nodemon app.js 
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    container_name: adminmongo
   
    ports:
      - "1234:1234"



